info:
  name: Delete role
  type: http
  seq: 119

http:
  method: DELETE
  url: "{{urlBase}}/api/index.php/roles/{{process.env.TEST_ROLE_ID}}"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false

assert:
  - res.status: eq 200
